// File generated by FlutterFire CLI.
// This is a placeholder file. Run `flutterfire configure` to generate
// the actual configuration with your Firebase project credentials.
//
// Run this command:
// ```bash
// flutterfire configure --project=your-firebase-project-id
// ```
//
// After running the command, replace this file with the generated one.

import 'package:firebase_core/firebase_core.dart';

/// Default Firebase options for web platform.
///
/// Placeholder values - will be replaced by flutterfire configure
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return const FirebaseOptions(
      apiKey: 'AIzaSyA-CuQJ658wKC2jhLPlRbKoIK6upzY2uxQ',
      appId: '1:526663635643:web:5f306f8d57d7fc0c7b0f9e',
      messagingSenderId: '526663635643',
      projectId: 'vacansee-68128',
      authDomain: 'vacansee-68128.firebaseapp.com',
      storageBucket: 'vacansee-68128.appspot.com',
    );
  }
}
